[package]
name = "advent19"
version = "0.1.0"
authors = ["nmryan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon="*"
